[package]
name = "crafting-hotkeys"
version = "0.3.0"
title = "Crafting Hotkeys"
author = "figsoda"
homepage = "https://github.com/figsoda/crafting-hotkeys"
factorio_version = "1.1"
description = "Adds hotkeys to craft items from your cursor or your quickbar. "

[deps]
base = ">= 1.1.0"
